version: "3"
services:
  web:
    image: nginx
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2000M
        reservations:
          memory: 1000M
      placement:
        constraints: [node.role == worker]
